name: cake_flutter
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Polyhedra-Studio/Cake-Flutter.git
publish_to: http://butterfree.lan:30117

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tools:
    sdk: flutter
  cake:
    version: ^5.5.2
  flutter_test:
    sdk: flutter

dev_dependencies:
  polyhedra_lint:
    version: ^1.0.4

flutter:
