name: cake_flutter
description: The lightweight, explicit testing framework - built for Flutter.
version: 0.4.0
homepage: https://github.com/Polyhedra-Studio/Cake-Flutter.git

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tools:
    sdk: flutter
  cake:
    version: ^6.0.1
  flutter_test:
    sdk: flutter

dev_dependencies:
  polyhedra_lint:
    version: ^1.0.4

flutter:
